version: '2.3'

services:

  lab:
    runtime: nvidia
    init: true

    privileged: true
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864

    environment:
      - JUPYTER_TOKEN
      - TENSORBOARD_URL_PREFIX=/tensorboard
      - PYTHONWARNINGS=ignore

  nginx:
    image: nginx:1.15.12-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf