version: '2.3'
services:
  lab:
    image: c-mg-01-v3-task3:v1.2.0
  assessment:
    image: c-mg-01-v3-task3-assessment:v1.2.0
    ports:
    - 8080:8080
  nginx:
    ports:
    - 80:80
    depends_on:
    - lab